spring:
  datasource:
    username: postgres
    password: xudoyshukur0102
    url: jdbc:postgresql://localhost:5432/crud
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 80
